# Generated by Django 4.2.5 on 2023-10-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id_pagina', models.AutoField(db_column='Id_Pagina', primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=100, null=True)),
                ('name_servers', models.CharField(blank=True, max_length=100, null=True)),
                ('registrar', models.CharField(blank=True, max_length=100, null=True)),
                ('registrant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registrant_city', models.CharField(blank=True, max_length=80, null=True)),
                ('registrant_state', models.CharField(blank=True, max_length=80, null=True)),
                ('registrant_country', models.CharField(blank=True, max_length=80, null=True)),
                ('admin', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_city', models.CharField(blank=True, max_length=80, null=True)),
                ('admin_country', models.CharField(blank=True, max_length=80, null=True)),
                ('admin_state', models.CharField(blank=True, max_length=80, null=True)),
                ('tech_name', models.CharField(blank=True, max_length=80, null=True)),
                ('tech_city', models.CharField(blank=True, max_length=80, null=True)),
                ('tech_state', models.CharField(blank=True, max_length=80, null=True)),
                ('tech_country', models.CharField(blank=True, max_length=80, null=True)),
                ('biling_name', models.CharField(blank=True, max_length=80, null=True)),
                ('biling_city', models.CharField(blank=True, max_length=80, null=True)),
                ('biling_state', models.CharField(blank=True, max_length=80, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Pagina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(db_column='Id_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=150, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=50, null=True)),
                ('contraseña', models.CharField(blank=True, db_column='Contraseña', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='Id_Usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='trustme_test.usuarios')),
                ('comentario', models.CharField(blank=True, db_column='Comentario', max_length=300, null=True)),
            ],
            options={
                'db_table': 'Opinion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rfc',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='Id_Usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='trustme_test.usuarios')),
                ('rfc', models.CharField(blank=True, db_column='RFC', max_length=50, null=True)),
                ('estatus', models.CharField(blank=True, db_column='Estatus', max_length=100, null=True)),
            ],
            options={
                'db_table': 'RFC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id_pagina', models.OneToOneField(db_column='Id_Pagina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='trustme_test.pagina')),
                ('estatus', models.CharField(blank=True, db_column='Estatus', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Validacion',
                'managed': False,
            },
        ),
    ]
